### ISSUE TITLE
问题：能否提升单服务互相调用的吞吐量？

### ISSUE THREAD

**Issue by pc859107393** [alibaba/alibaba-rsocket-broker#102]
**问题描述**
这两天在做压测，目前我们单机性能瓶颈是 95请求/40ms 左右，并且后续性能难以提升。首先，我们是服务粘性调用，按照常规理解，我们提升服务数量就能提高吞吐量，实际发现并不是。 首先无论是什么服务哪怕是broker，实际工作中只有一个 actor-tcp-nio 在参与工作。目前暂未定位到源码是哪里限制了其他线程参与服务通信相关工作。

经过仔细分析，再次验证了猜想。咱这个项目需要的是单服务多节点部署的模式。可能是因为服务内部采用了socket类似通信机制的原因，在服务启动后，可以理解为服务A和B建立了一个固定通道，所有的服务数据都是走的这个固定通道，所以当单个远程服务B的单链接超过极限后，再难以提升吞吐量.

整理了思路后，我这边回顾了一下LoadBalancedRSocket相关的代码，发现在 Mono<RSocket> connect(String uri) 这个方法里面实现了微服务之间的链接，能否在这里实现 服务之间多路链接，然后 调用方根据需要选择 链接 实现服务吞吐量的提升呢？

**Comment by pc859107393** [comment]
目前通过调整Proxy和Hook，以及添加了LinkedSelector 已经实现服务调用方的请求多路复用。正在查看broker转发这里的多路复用。根据目前查看到的LoadBalancedRSocket源码来讲，要实现较好的多路复用策略还需要把这里优化一下。

**Comment by linux-china** [comment]
>> 所有的服务数据都是走的这个固定通道，所以当单个远程服务B的单链接超过极限后

这个长连接是多路复用的，如果有瓶颈限制，估计就是网卡啦，而且单个长连接是对MTU友好的。 

你可以同时启动两个broker，然后对比测试一下，看一下两个broker是否对吞吐量的影响。
