### ISSUE TITLE
Unified management of magic numbers

### ISSUE THREAD

**Issue by kevinten10** [alibaba/alibaba-rsocket-broker#103]
I saw these codes when i reading the code.

You use a lot of magic numbers of `String `type.

E.g
```java
public class ReactiveMethodMetadata extends ReactiveMethodSupport {
     public static final List<String> STREAM_CLASSES = Arrays.asList("io.reactivex.Flowable", "io.reactivex.Observable",
             "io.reactivex.rxjava3.core.Observable", "io.reactivex.rxjava3.core.Flowable", "reactor.core.publisher.Flux",
             "kotlinx.coroutines.flow.Flow");
```

I can understand that this is an irregularity caused by rapid development?

The consequence is that this will make subsequent updates difficult to maintain , and irregular code format.

Whether to consider unified management of this type of magic number?

For example, use "constant management class".
```java
public interface ModuleConstantsManager {

     interface RxJavaConstants {

         List<String> CLASSES = Arrays.asList("io.reactivex.rxjava3.core.Observable");
     }
}
```

This will improve the standardization of the project.

I would be happy to do this part if needed.

**Comment by linux-china** [comment]
@kevinten10  PR welcome  :)

**Comment by linux-china** [comment]
merged.
