### ISSUE TITLE
在broker内向客户端推送信息失败

### ISSUE THREAD

**Issue by pc859107393** [alibaba/alibaba-rsocket-broker#117]
在broker内向客户端发送推送消息失败，具体代码是调用了RSocketBrokerResponderHandler内的fireCloudEventToPeer方法，发送消息失败，简单的看了一下代码，这里没有产生 subscribe 调用或者是 block 调用，看了一下外部其他的调用地方实现了对应的这个subscribe调用。

**Comment by pc859107393** [comment]
感觉这里调整成内部 订阅，操作成功后创建一个Mono.empty();返回可能效果不错，更加方便使用。

**Comment by linux-china** [comment]
如果你推送一个事件到客户端，客户端需要创建一个对应的Processor来消费对应的事件，不然客户接收到该事件后不知道该如何处理，只能扔掉。 详细的样例请参考  InvalidCacheEventProcessor  和  InvalidCacheEvent 。 

另外你说的是正确的，目前的事件订阅确实比较麻烦，我重新设计一下对应的接口，更方便使用。 准备添加一下以下接口，你只要实现该Bean，就可以消费从broker端推送来的事件。

```
public interface CloudEventsConsumer {

    Mono<Boolean> shouldAccept(CloudEventImpl<?> cloudEvent);

    Mono<Void> accept(CloudEventImpl<?> cloudEvent);
}
```

**Comment by linux-china** [comment]
如果还有这样的问题，再reopen一下，谢谢！
