### ISSUE TITLE
应用端到Broker集群的Load Balance架构和稳定性

### ISSUE THREAD

**Issue by linux-china** [alibaba/alibaba-rsocket-broker#12]
目前RSocket主要涉及到的Load Balance到Broker 集群的多连接管理。 Alibaba RSocket Broker采用share nothing架构，也就是集群中broker相互之间不通讯，不承担消息转发。 目前客户端SDK的设计思路是通过集群推过来的拓扑结构变更，SDK端完成连接的重连和路由更新等。 目前代码只有基础功能，需要再细致完善，提升稳定性。

**Comment by linux-china** [comment]
目前的方案是健康度检查  和 实时调用时的connection检查，结构已经进行了调整。

**Comment by cangxingzhe** [comment]
是客户端SDK进行负载，broker做注册中心的意思吗

**Comment by linux-china** [comment]
客户端已经和broker建立连接啦，这个连接同时就是服务注册。  RSocket是基于一个长连接进行异步消息通讯的，没有http那种连接池的概念，所以客户端的SDK的负载均衡就是和多个broker建立连接，然后调用随机发送给某一broker，防止一个broker接收的消息太多，影响系统的性能。 @cangxingzhe

**Comment by cangxingzhe** [comment]
好的，谢谢你的回复。我描述有些粗糙，看了spring cloud rsocket，他的客户端只能和broker建立一个长连接，因为它还在孵化中，所以对应它的设计思路，有两种才行
1.它的客户端会支持负载均衡
2.每一个客户端有一个唯一的broker，然后这个broker再和broker集群建立连接
这些是我猜想哈，我这几天在研究Alibaba，到时再请求大佬
