### ISSUE TITLE
编译错误：npm ERR! Unexpected end of JSON input while parsing near '...2oYSQ4\nrAd/cAHSAmngL'

### ISSUE THREAD

**Issue by wyfn18** [alibaba/alibaba-rsocket-broker#13]
[INFO] Added 40 dependencies to 'D:\IdeaProjects\alibaba-rsocket-broker\alibaba-broker-server\target\frontend\package.json'
[INFO] Updated npm D:\IdeaProjects\alibaba-rsocket-broker\alibaba-broker-server\target\frontend\package.json.
[INFO] Running `npm install` ...
npm ERR! Unexpected end of JSON input while parsing near '...2oYSQ4\nrAd/cAHSAmngL'

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\Program Files\nodejs\node_cache\_logs\2019-12-16T05_49_17_435Z-debug.log
[ERROR] >>> Dependency ERROR. Check that all required dependencies are deployed in npm repositories.
---------------------------------------------------------------------------------------------------
maven 版本 ：3.63
nodejs 版本：v12.13.1

是不是我本地网络比较慢，包下载的不完整？

**Comment by linux-china** [comment]
我使用了一个全新的环境进行了编译，都完全正常。 你尝试不要使用国内的npm镜像，然后重新编译一下试试。

**Comment by wyfn18** [comment]
确实是镜像问题，我使用taobao镜像编译成功，命令如下：
npm config set registry https://registry.npm.taobao.org
