### ISSUE TITLE
无法k8s下载镜像

### ISSUE THREAD

**Issue by namehuxing** [alibaba/alibaba-rsocket-broker#130]
**Describe the bug**

### Environment

* Alibaba RSocket Broker version: 1.0.0.M2
* Operating System version: Linux/Windows 10/Mac
* Java version: 1.8.0/11.0.7/14.0.1

### Steps to reproduce this issue
无法下载镜像
![image](https://user-images.githubusercontent.com/7345460/119782850-3c261a00-beff-11eb-88b5-3c741deb6c16.png)
Pls. provide GitHub address to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Please post your stack trace here!
```

**Comment by linux-china** [comment]
Please use last linuxchina/alibaba-rsocket-broker:1.1.0-k8s , and 1.0.0.M2 has been deprecated, thanks.
