### ISSUE TITLE
如何在非Spring环境设置 rsocket.topology=internet 参数

### ISSUE THREAD

**Issue by yangjungis** [alibaba/alibaba-rsocket-broker#134]
如何在非Spring环境设置 rsocket.topology=internet 参数

我直接使用的 RSocketBrokerClient 和 RSocketBrokerConnector ， 如果设置 rsocket.topology=internet

**Comment by linux-china** [comment]
Add top topology for RSocketBrokerConnector   #1cfeca8c1b649ced614f158c07e4c5a6bdc921d8

**Comment by yangjungis** [comment]
方法能否再灵活点，能否提高一个KV简直对进行元信息添加。

**Comment by linux-china** [comment]
Spring boot应用中可以设置的，但是对于普通的Java应用，不知道如何做更方便。 dotEnv？  能否给一个思路？ :)

**Comment by pc859107393** [comment]
> 方法能否再灵活点，能否提高一个KV简直对进行元信息添加。

不知道你的意思是不是写个自定义的yml或者是json文件来定义这个

**Comment by linux-china** [comment]
> > 方法能否再灵活点，能否提高一个KV简直对进行元信息添加。
> 
> 不知道你的意思是不是写个自定义的yml或者是json文件来定义这个

那就太麻烦啦。 rsocket-core中不想引入太多的东西，如果大家觉得内部产品还可以再包装一下，可以考虑结合yaml或者json自己做一个build包装一层。  :)

**Comment by yangjungis** [comment]
RSocketBrokerConnector
                .create()
                .appName("MockApp")
                .topology("internet")
                .addMeta("k1","v1")
                .addMeta("k2","v2")

**Comment by linux-china** [comment]
metadata() API added 

```
 public RSocketBrokerConnector metadata(String name, String value)
```

**Comment by yangjungis** [comment]
broker 在DOCKER 环节启动， 环境遍历如下
```
JAVA_VERSION_BUILD=14
HOSTNAME=b128864fc2d9
TERM=xterm
JAVA_VERSION_MAJOR=8
GLIBC_VERSION=2.23-r3
JAVA_OPTS=-Xms2g -Xmx2g
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk/bin
PWD=/opt/docker
JAVA_HOME=/opt/jdk
RSOCKET_BROKER_EXTERNAL_DOMAIN=rsocket.ytd.com
LANG=C.UTF-8
SHLVL=1
HOME=/root
JAVA_PACKAGE=jdk
JAVA_VERSION_MINOR=92
_=/usr/bin/env
```
broker client 应用 
```
rsocket.topology=internet
```

后续的连接还会使用内部地址

```
c.a.r.l.LoadBalancedRSocket in reactor-tcp-nio-6 - RST-500408: RSocket reconnect failed: 12 tcp://172.17.0.9:9999
```
