### ISSUE TITLE
是否考虑支持跨集群broker之间长连接通信方案

### ISSUE THREAD

**Issue by AtticusLv** [alibaba/alibaba-rsocket-broker#135]
如题，业务目前有诉求需要两个集群之间进行通信，如集群A中X服务调用集群B中Y服务，集群A和B中均通过rsocket broker的方式实现了服务注册和发现，A broker和B broker直接如何进行通信呢？

或者有什么好的方案来实现这种业务诉求

感谢大佬！

**Comment by tingyanshen** [comment]
SharedNoting 下的实现，broker 之间的通讯是否有必要？ 可以参考 [rsocket-routing](https://github.com/rsocket-routing/rsocket-routing) 的文档，是支持 broker 转发的设计。

如果只是考虑了需求，也可以考虑不直接使用broker实现。可以让连接到broker的一个专门的服务去做这件事情。

**Comment by pc859107393** [comment]
为什么这种情况不使用更加专业的mq呢发自我的华为手机-------- 原始邮件 --------发件人： Tingyan Shen ***@***.***>日期： 2021年7月7日周三 16:02收件人： alibaba/alibaba-rsocket-broker ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [alibaba/alibaba-rsocket-broker] 是否考虑支持跨集群broker之间长连接通信方案 (#135)

SharedNoting 下的实现，broker 之间的通讯是否有必要？ 可以参考 rsocket-routing 的文档，是支持 broker 转发的设计。

如果只是考虑了需求，也可以考虑不直接使用broker实现。可以让连接到broker的一个专门的服务去做这件事情。

**Comment by linux-china** [comment]
支持这个特性的，请参考一下 https://github.com/alibaba/alibaba-rsocket-broker/wiki/RSocket-Broker-Clusters  但是你要规划一下集群，文中有说明， 如果只有两个集群的话，可以设置为父子集群，如果你上述的需求，可以将B设置中心的集群就可以。
