### ISSUE TITLE
有roadmap的么？

### ISSUE THREAD

**Issue by silencecorner** [alibaba/alibaba-rsocket-broker#17]
有roadmap话，我们这些菜鸟更方便参与进来^_^

**Comment by linux-china** [comment]
目前RSocket Broker的主要工作：

* RSocket了解的同学还比较少，所以我们还是要先让同学了解RSocket， http://rsocketbyexample.com
* Alibaba RSocket Broker的产品问题，这个在编写中，会尽快同步给大家
* RSocket Broker的集群管理，基于Gossip的特性还在测试中
* RSocket Broker控制台开发，目前这个控制台的功能还比较简单
* RSocket Java SDK 1.0.0正式版还没有发布，这个还需要等
* Alibaba RSocket Broker和Spring RSocket的兼容，也就是通过Spring Boot RSocket原生应用就可以注册/调用RSocket Broker服务
* Reactive的普及力度还不够，我们还要做一些Reactive相关的普及工作
* RSocket多语言SDK兼容开发：目前主要关注的是 Node.js, Python, Golang和Rust，这个要在RSocket的数据编码规范确认后进行

**Comment by silencecorner** [comment]
thx!
