### ISSUE TITLE
requester.route("com.alibaba.user.UserService.findById").data(id).retrieveMono(User.class)设计成函数式会不会更舒服点

### ISSUE THREAD

**Issue by YAGAMIL** [alibaba/alibaba-rsocket-broker#176]
![image](https://user-images.githubusercontent.com/16757285/142830958-4c282269-d6d3-4241-934b-bbc44001f93c.png)
`requester.route<User>( () -> userService.findById(id)).retrieveMono();`

**Comment by linux-china** [comment]
这个主要是告知开发者如何使用Spring RSocketRequester调用RSocket Broker上的服务，并不是为了追求代码的精简，大家可以在RSocketRequester至少进行自己的封装，如 https://github.com/spring-projects-experimental/spring-retrosocket
