### ISSUE TITLE
建议broker-server和vaadin拆分成两个工程

### ISSUE THREAD

**Issue by atshow** [alibaba/alibaba-rsocket-broker#179]
建议broker-server和vaadin拆分成两个工程:
broker-server可以只使用webflux来实现restful请求.
vaddin作为前端框架使用.
方便扩展和替换前端

**Comment by atshow** [comment]
我本人的机器是windows7  无法运行nodejs14及以上的版本,本意是更希望 broker-server不依赖vaadin,直接提供静态文件包.

**Comment by linux-china** [comment]
如果你需要一个轻量级的Broker Server的话，可以直接创建一个Spring Boot应用，然后引用 alibaba-broker-spring-boot-starter，然后再application.properties中添加一下一下配置即可。 RSocket Broker Starter就是用来被嵌入的，你可以更加自己的需要开发对应的UI和Ops API。

```
rsocket.broker.listen=9999
rsocket.broker.topology=standalone
#rsocket.broker.seeds=192.168.11.11,192.168.11.12,192.168.11.13
# Please make auth-required true on production env
rsocket.broker.auth-required=false
```
