### ISSUE TITLE
多语言支持？

### ISSUE THREAD

**Issue by kooksee** [alibaba/alibaba-rsocket-broker#183]
最近在研究rsocket，然后发现了alibaba-rsocket-broker这个非常棒的项目，想做一些测试，然后发现这边只支持java，没有golang相关的demo或者sdk。

想问下，咱们这边有多语言或者go语言开发的计划吗？

**Comment by linux-china** [comment]
标准的RSocket SDK就支持，你看一下  https://github.com/alibaba/alibaba-rsocket-broker/blob/master/alibaba-rsocket-core/src/main/java/com/alibaba/rsocket/client/RSocketBrokerClient.java 的实现，只需要发几个metadata就可以。  RSocket本身就是为Broker设计的，不需要对SDK进行特殊调整 :)
