### ISSUE TITLE
非 spring 环境下的示例

### ISSUE THREAD

**Issue by iohao** [alibaba/alibaba-rsocket-broker#188]
请问有非 spring 环境下的完整示例吗，example 目录下好像都是 spring 环境的。

**Comment by linux-china** [comment]
参考这里 https://github.com/alibaba/alibaba-rsocket-broker/blob/master/alibaba-rsocket-core/src/test/jbang/RSocketBrokerClientApp.java   ， 独立Java应用接入的范例。

**Comment by iohao** [comment]
谢谢
