### ISSUE TITLE
关于 broker 的正确使用方式

### ISSUE THREAD

**Issue by iohao** [alibaba/alibaba-rsocket-broker#189]
请教一个关于 broker 如何正确使用的问题，有下面两种场景。

第一种方式：
假如有 100 个手机 app（IM），是这100个app直接与 broker 建立连接呢。

第二种方式：
还是这100个 app 与 netty的服务器建立连接，而在这 netty 服务器中创建一个消费者（Requester）与 broker 建立连接呢。

正如 https://github.com/alibaba/alibaba-rsocket-broker/wiki/RSocket-SDK-LoadBalance 中的服务消费者这一节说的，服务消费者会和10台服务(broker，假设有10台broker)建立连接。

是不是使用 第二种方式 会好一些。

如果应用对实时性比较高，可以用 alibaba-rsocket-broker 吗，不是网页那种应用。

**Comment by linux-china** [comment]
最好使用第二种方式，对应手机app连接到broker，这个可能涉及到安全验证，所以通过一个统一的Requester然后和Broker进行交互会是比较好的方案。 此外手机App的数量比较大，会创建大量的连接，而统一的requester也方便扩容，而broker集群本身并不需要特别多的数量的，不用担心broker集群扩容的问题。

**Comment by iohao** [comment]
谢谢

**Comment by iohao** [comment]
在另外问一个问题，在业务处理中。如何得到当前登录用户的数据（如：userId 等）这些。因为接口支持一个业务参数，当每次请求的时候，是要把用户的数据都编写到这个自定义的业务参数中吗。

**Comment by linux-china** [comment]
>> 如何得到当前登录用户的数据（如：userId 等）这些
Web应用会根据cookie或sessionId获取登录用户信息的，然后你验证用户后基于用户id调用对应的服务接口就可以，如findUserById(id)这样。

**Comment by iohao** [comment]
好的，谢谢！

**Comment by sdack-cloud** [comment]
> 如何得到当前登录用户的数据（如：userId 等）这些。因为接口支持一个业务参数，当每次请求的时候，是要把用户的数据都编写到这个自定义的业务参数中吗



> 最好使用第二种方式，对应手机app连接到broker，这个可能涉及到安全验证，所以通过一个统一的Requester然后和Broker进行交互会是比较好的方案。 此外手机App的数量比较大，会创建大量的连接，而统一的requester也方便扩容，而broker集群本身并不需要特别多的数量的，不用担心broker集群扩容的问题。

broker  不就是承载大量来自app的连接的吗？如果不承载大量连接，broker 并发数 达到百万级有什么意义呢？
> 像微服务 gateway 不就承载来自 客户端的连接 嘛，所以 gateway 就一个
还有最想问的是 安全与认证  oauth2 这块如何规划的
@linux-china

**Comment by linux-china** [comment]
>> broker 不就是承载大量来自app的连接的吗？如果不承载大量连接，broker 并发数 达到百万级有什么意义呢？

外部的连接最好走一个Gateway，还是Broker，但是和内部的Broker集群不一样。 Nginx也是支持非常大的并发的，但是我们在实际部署时，也是有内部的Nginx Gateway的，然后是Nginx + Spring Boot这样的结构。

>>  安全与认证 oauth2 这块如何规划的
这个看你具体的设计，RSocket Broker的安全验证只需要包含Token，然后具体的验证逻辑，你可以对接OAuth2 Server进行验证就可以啦。
