### ISSUE TITLE
broker 可以作为网桥吗 ？network bridge 或 RSocket Bridge 

### ISSUE THREAD

**Issue by sdack-cloud** [alibaba/alibaba-rsocket-broker#199]
有这样一个需求：
      一台电脑可以接入 100W长链接，如果想要接入更多，需要更多电脑
      如果有一个网桥 可以把他们连接起来，从A电脑进来的消息要投送至B电脑的接入者。网桥负责中间转发消息。
      broker 可以作为网桥吗？？？ @linux-china

**Comment by linux-china** [comment]
最好不要这样做，Broker是内部应用相互之间通讯的代理，主要用于服务之间的通讯。 如果是网关或者网桥的场景，最好使用RSocket Gateway，每一个RSocket Gateway支持100W连接，然后多增加几个Gateway服务器就可以，然后这些Gateway再作为普通应用接入到Broker就可以。 对比Broker，Gateway简单不少，最好不要将Broker作为Gateway使用。 这个讨论也说明了， https://github.com/alibaba/alibaba-rsocket-broker/discussions/196   就是使用Broker IM的接入端，也不建议这样使用。

**Comment by sdack-cloud** [comment]
> 从A电脑进来的消息要投送至B电脑的接入者。网桥负责中间转发消息。

RSocket  Gateway只是 一台电脑的接入者，A电脑进来的消息要投送至N多台电脑的Gateway然后转发出去 消息需要 Bridge 介入中转。

所有的Gateway （接入者）都要注册至Bridge 和 Broker。Bridge 会知道那台电脑谁（用户）接入了，应该将消息转发给那台电脑的Gateway，Gateway在投送至用户。 Broker 是后面的服务和数据层，用来服务调用。  Bridge 也是信息中转的作用，和Broker很像

RSocket Gateway 现在并没有开源的项目，您能推荐下RSocket Gateway 好的项目吗？？
我也是在学习Broker 源码来写一个Bridge 

Bridge 这样的设计很缺啊。把所有电脑连接到一起的设计，Bridge 有没有开发计划啊？？？@linux-china

**Comment by linux-china** [comment]
消息转发这个属于IM的范畴，这个技术已经非常成熟了，每一个用户接入到Gateway，Gateway会通过一个中间存储来保存登录用户的信息的，如用户名/ID, 登录IP，登录时间，接入的Gateway Server等，你发消息的时候，会拿到这些信息然后向指定的Gateway Server服务发送信息的，然后Gateway Server会将消息转发给登录的用户的，这种消息转发是不需要经过Broker的，直接在Gateway集群内部就完成啦，经过Broker反而有性能损失，还要维护那么多的元信息。

Slack的架构设计网上都能查到的，下图中的Presence Server就是负责存储用户的登录后的信息的，如下图： 

![image](https://user-images.githubusercontent.com/46711/180627428-aea51f6d-904a-43ca-9743-b38c57ddeda0.png)


Scaling Slack - The Good, the Unexpected, and the Road Ahead： https://www.youtube.com/watch?v=_M-oHxknfnI

**Comment by sdack-cloud** [comment]
网关：Gateway Server (Spring RSocket来做)

网桥：Channel Server（Kafka）

其实Kafka 就是我所说的 network bridge，它把消息分配至各各网关，不用再去写一个network bridge的东西

我理解的对吗

**Comment by linux-china** [comment]
Presence Server: 这个可以使用Redis来做，就是保存登录用户的信息，方便进行消息路由。

**Comment by sdack-cloud** [comment]
RSocket 不是可以选择WebSocket 协议 还是 tcp协议的嘛？
我是想用 RSocket做 IM网络通讯协议
RSocket 在IM场景下 不可以嘛 ？？？
我看也推出了 rsocket-dart 。可以做 flutter 的SDK @linux-china

**Comment by sdack-cloud** [comment]
RSocket 不是可以选择WebSocket 协议 还是 tcp协议的嘛？
我是想用 RSocket做 IM网络通讯协议
RSocket 在IM场景下 不可以嘛 ？？？
我看也推出了 rsocket-dart 。可以做 flutter 的SDK @linux-china

**Comment by linux-china** [comment]
考虑到客户端的复杂环境、浏览器支持、防火墙等因素，建议选择WebSocket的。   RSocket当然可以做IM通讯协议。

**Comment by sdack-cloud** [comment]
Spring RSocket 如何测试单机能达到多少长连接 能给一些建议嘛 @linux-china

**Comment by linux-china** [comment]
这个主要看硬件配置，RSocket底层使用Netty，你可以进行一下测试，一般的服务器，30-50W并发连接完全没有问题。

**Comment by sdack-cloud** [comment]
我在使用 js 连接RSocket 服务器，服务器是websocket协议

```
let ws = new WebSocket("ws://localhost:7002");
```

但是发现连接失败，在网上也很难找到js 连接RSocket 的示例

我想服务端是websocket  js 与其连接不是顺其自然吗

我做这方便的尝试是 为了 微信小程序接入做准备
@linux-china

**Comment by linux-china** [comment]
你最好看一下RSocket-JS项目，虽然RSocket-JS很简单，但是还是要知道原理的，不然贸然开发应用，以后可能有问题。 WebSocket接入样例请参考：  https://github.com/rsocket/rsocket-js/blob/1.0.x-alpha/packages/rsocket-examples/src/ClientServerRequestStreamExampleWebSocket.ts

**Comment by sdack-cloud** [comment]
我在使用spring rsocket 和 protobuf 作通信测试


No decoder for io.pivotal.rsocketclient.data.MetaVo$Meta
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
序列化报错

客户端
```

    @ShellMethod("Login with your username and password.")
    public void login(String u, String p) {
        log.info("Connecting using client ID: {} and username: {}", CLIENT_ID, u);

        this.rsocketRequester = rsocketRequesterBuilder
                .setupRoute("connect")
                .setupData(CLIENT_ID)
                .rsocketStrategies(builder ->
                        {
                            builder.encoder(new ProtobufEncoder(),new SimpleAuthenticationEncoder())
                            .decoder( new ProtobufDecoder());
                        }
                )
                .connectWebSocket(URI.create("ws://localhost:7002"))
                .block();

    @ShellMethod("Send one request. One response will be printed.")
    public void requestResponse() throws InterruptedException {
        if (userIsLoggedIn()) {
            log.info("\nSending one request. Waiting for one response...  request-response");

            MetaVo.Meta.Builder builder = MetaVo.Meta.newBuilder();
            builder.setRemark("你好").setV(5.56).setAppId(888);
            MetaVo.Meta build = builder.build();
            MetaVo.Meta message = this.rsocketRequester
                    .route("toOne")
                    .data(build)
                    .retrieveMono(MetaVo.Meta.class)
                    .block();
            log.info("\nResponse was: {}", message);
        }
    }

```

服务端
```
    @MessageMapping("toOne")
    fun toOne(request: MetaVo.Meta): Mono<MetaVo.Meta> {
        return Mono.just(request)
    }

```
找了一圈人家怎么配置的 也没找到结果。希望您解答
@linux-china

**Comment by linux-china** [comment]
目前Spring RSocket还不支持Protobuf，你使用json先测试一下。

**Comment by sdack-cloud** [comment]
那这两个类是做什么的，支持Http协议
import org.springframework.http.codec.protobuf.ProtobufDecoder;
import org.springframework.http.codec.protobuf.ProtobufEncoder;
@linux-china

**Comment by linux-china** [comment]
Spring RSocket详细的你参考一下 https://docs.spring.io/spring-framework/docs/current/reference/html/rsocket.html   你先不用在意数据序列化，先确保这个流程是可行的，然后到具体的数据序列化，这个都是可以做的。 

这个是ProtobufDecoder的，这个你也是可以使用的，但是要求对应的Java对象都是Protobuf Message，然后才能从bytes转换到对应的Protobuf Message对象，详细的你查下文档。

**Comment by sdack-cloud** [comment]
刚刚我做了尝试
将数据已 ByteArray 进行传输 能得到我想要的结果


```
客户端

MetaVo.Meta.Builder builder = MetaVo.Meta.newBuilder();
            builder.setRemark("你好").setV(3.5);
            MetaVo.Meta build = builder.build();
            MetaVo.Meta message = this.rsocketRequester
                    .route("toOne")
                    .data(build.toByteArray())
                    .retrieveMono(MetaVo.Meta.class)
                    .block();

服务端

    @MessageMapping("toOne")
    fun toOne(request: ByteArray): Mono<Any> {
        log.debug("收到")
        val parseFrom = MetaVo.Meta.parser().parseFrom(request)
        log.debug("收到{}",parseFrom)
        return Mono.just(request)
    }
```

parseFrom() 方法 提示 会阻塞，那应该怎么使用
@linux-china

**Comment by linux-china** [comment]
这个警告忽略就可以，没有大问题。

**Comment by sdack-cloud** [comment]
> val parseFrom = MetaVo.Meta.parser().parseFrom(request)

这个不会阻塞线程吗
@linux-china

**Comment by sdack-cloud** [comment]
> val parseFrom = MetaVo.Meta.parser().parseFrom(request)

这个不会阻塞线程吗
@linux-china

**Comment by linux-china** [comment]
Protobuf的序列化和反序列化非常快的，而且ByteArray对应的字节流已经在内存中啦，不用担心这个阻塞。

**Comment by sdack-cloud** [comment]
rsocket-js
使用 rsocket-websocket-client

如何传递 token 信息 建立连接
如spring 
```
org.springframework.security.rsocket.metadata.BearerTokenMetadata
org.springframework.security.rsocket.metadata.UsernamePasswordMetadata
```
@linux-china

**Comment by linux-china** [comment]
[Getting Started With RSocket: Spring Security](https://spring.io/blog/2020/06/17/getting-started-with-rsocket-spring-security)

**Comment by sdack-cloud** [comment]
不，我是说 使用 rsocket-websocket-client 如何传递 Bearer {Token}

spring-rsoccket-demo 我看懂了，只是没找到 js 这边如何传递的demo
@linux-china

**Comment by linux-china** [comment]
安全规范 https://github.com/rsocket/rsocket/blob/master/Extensions/Security/Authentication.md  是RSocket Composite Metadata的一部分，在Composite Metadata添加一下即可，RSocket JS已经包含安全相关的metadata  https://github.com/rsocket/rsocket-js/tree/1.0.x-alpha/packages/rsocket-composite-metadata/src
如何在Client/Server之间传递composite metadata，请参考： 
https://github.com/rsocket/rsocket-js/blob/1.0.x-alpha/packages/rsocket-examples/src/ClientServerCompositeMetadataRouteExample.ts

**Comment by sdack-cloud** [comment]
rsocket-dart 现在可以支持 authentication嘛?????? 我看版本是 0.1.2

我的意思是比较 开箱即用的，像spring 一样封装成对象

rsocket-js 的案例很多是 ts的语法，有些看不懂啊

> Composite Metadata 

我已经引入了 npm i rsocket-composite-metadata

```
import {
  decodeCompositeMetadata,
  decodeRoutes,
  decodeAuthMetadata,
  encodeCompositeMetadata,
  encodeRoute,
  WellKnownMimeType,
  encodeSimpleAuthMetadata
} from "rsocket-composite-metadata";

```

```java

    @ConnectMapping("connect")
    fun connect(requester: RSocketRequester, @Payload client: String) {
        requester.rsocket()
            ?.onClose()
            ?.doFirst {
                log.info("Client: {} CONNECTED. Count: {}", client, clients.size)
                clients[client] = requester
                log.info("connected. Count: {}", clients.size)
            }
            ?.doOnError {
                // Warn when channels are closed by clients
                log.warn("Channel to client {} CLOSED. Count: {}", client, clients.size)
                clients[client]?.rsocket()?.dispose()
                log.warn("closed. Count: {}", clients.size)
            }
            ?.doFinally {
                log.warn("Client: {} DISCONNECTED. Count: {}", client, clients.size)
                clients.remove(client)
                log.warn("disconnected Count: {}", clients.size)
            }
            ?.subscribe()

        // TODO 服务端订阅客户端 message 方法，发送消息
    }

```
我的服务端 连接 在 connect 。
js 这块怎么写？？？？？

@linux-china
