### ISSUE TITLE
docker imgage for mac M1

### ISSUE THREAD

**Issue by sdack-cloud** [alibaba/alibaba-rsocket-broker#203]
有考虑制作macos M1 架构的镜像嘛
@linux-china

**Comment by linux-china** [comment]
这个不麻烦，我稍后完成提交一下。

**Comment by sdack-cloud** [comment]
![image](https://user-images.githubusercontent.com/49465225/184528366-f4adfab3-8eb3-4ee1-af43-ad02d8db9c15.png)

我运行了 容器
http://localhost:9998/  无法访问
@linux-china

**Comment by sdack-cloud** [comment]
docker run -d --name broker -p 9997:9997 -p 9998:9998 -p 9999:9999 linuxchina/alibaba-rsocket-broker:1.1.3-arm64
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by sdack-cloud** [comment]
![image](https://user-images.githubusercontent.com/49465225/184528780-8fb4d9eb-710c-435e-bdf2-7a2d56ee7b97.png)
