### ISSUE TITLE
坚持不懈数月只更新依赖版本号，真不愧KPI项目

### ISSUE THREAD

**Issue by geligaoli** [alibaba/alibaba-rsocket-broker#207]

**Comment by linux-china** [comment]
我已经从阿里巴巴离职啦，这些维护工作都是我现在个人行为。  不管项目特性如何发展，版本号更新这个必须做的事情，安全修复不用说，还要确保软件的兼容，这个是心跳，必须做的事情。 JDK版本兼容，Spring Boot兼容，GraalVM native-image兼容，Kotlin版本兼容等，这些在版本更新时都有检查的。 此外你还可以关注一下 https://github.com/alibaba-rsocket-broker/  相关的example等，也是在同步更新的。  如果大家觉得有什么特性不满足的，可以提需求，我会进行开发。定期的dependencies更新，也是告诉我在维护，我每天会用IntelliJ IDEA打开该项目，查看提交的issue，更新依赖，确保不要有一些安全和兼容问题，同时也会更新RSocket Example，确保不出现问题。

此外我个人还在维护一个dependencies每日更新的项目，就是确保一些最新版本的兼容，同时也了能了解Java业绩最新的动态，https://github.com/linux-china/platform-bom-contrib/commits/cairo  也让大家见笑啦。

**Comment by CoderYellow** [comment]
可惜了，最近还在学rsocket，上游项目还在活跃开发，但spring的[rsocket](https://github.com/spring-projects-experimental/spring-retrosocket.git)停更很久了，估计也毕不了业;
另一个[broker](https://github.com/rsocket-broker/rsocket-broker)也是spring cloud官方弃坑，员工也很久不维护。大公司失去了兴趣，感觉这个协议没什么前景了。

**Comment by linux-china** [comment]
@CoderYellow 事在人为，其实大多数很好的开源软件都是2-3人在维护，也不需要那么多人扑上去。 如果你觉得这个方向很好，就可以持之以恒。 我是不敢其他人如何看待的，我会持续支持RSocket的，可能投入没有那么多，也会持续更新的，这个就是个人的爱好。

**Comment by AhianZhang** [comment]
国内使用响应式编程的 Java 程序员少，从命令式编程切换成响应式需要一个思维的转变，公司项目还考虑整体的编码水平，
而且 RSocket 没有一款在某个领域能打的产品。
