### ISSUE TITLE
支持 @RSocketClient 注解

### ISSUE THREAD

**Issue by CoderYellow** [alibaba/alibaba-rsocket-broker#208]
既然有了 @RSocketService 注解，为什么不再加一个客户端的 @RSocketClient 注解，可以参考一下@FeignClient 实现

**Comment by linux-china** [comment]
能给一个样例代码吗？  @RSocketService Annotation主要使用在RSocket服务实现类上，便于Spring进行bean扫描。 不知道@RsocketClient这个注解用在什么地方？ 如果样例代码如下：

```java
public class XxxService {

   @RSocketClient
   private UserService userService;
}
```

那么相关配置还是需要的，如连接到到哪个broker集群上，对应的版本，encoding方式等，这个就和Dubbo的处理方式类似。

```
@Component
public class GreetingServiceConsumer {
    @Reference
    private GreetingService greetingService;

    public String doSayHello(String name) {
        return greetingService.sayHello(name);
    }
}
```

目前采用的是手动代码声明方式，这个方式相对比较灵活，如果方便设置集群，服务版本等，也比较容易实现一个服务接口对应两个版本，方便A/B测试。而且在实际的使用中，第三方调用对应的代码都是通过一个SDK完成的，如xxx-client-spring-boot-starter，而在该starter中会包括对应的bean声明，这个大家也都明白的，就是一个Auto Configution，而使用方只需要 `@AutoWired private UserService userService`这样即可，采用标准的Spring Bean方式进行诸如，如果你以后觉得RSocket不好，你调整一下对应的bean实现就可以，完全不需要去代码中找寻 `@RSocketClient`这些代码然后进行删除。  当然不提供 `@RSocketClient` 也是为了方便代码迁移到 RSocket上，之前的bean引用不需要做任何修改，服务提供方只要提供一个Auto Configuration就完成服务的替换啦，而不需要开发人员去找哪些接口然后添加对应的annotation。

这是两种编码方式，如果觉得确实RSocketClient这种注解方式比较好，也可以考虑的，没有太多的技术难度。

**Comment by CoderYellow** [comment]
我感觉注解声明式风格肯定要比写一堆boilerplate code好，用过feign的人比较容易接受的是在接口上加注解，这是我抄的一个[demo](https://github.com/MicroJService/micronaut-rsocket/blob/dev/example/user-service-api/src/main/java/org/microjservice/user/AccountService.java)。

如果觉得api interface是server和client的公共依赖，不想加注解，也可以考虑搞个`@EnableRSocketClient`注解，参考@ComponentScan注解，支持正则和aspectj风格的包名扫描，把扫描的接口实现然后注册bean。

要实现多样化配置也尽量不要硬编码，应该放到配置文件里，用springboot的auto config。对于最后的一种场景可以考虑在`@RSocketClient`加个`contexts`数组参数，支持实现多个bean：
```java

```

**Comment by CoderYellow** [comment]
单元测试方面spring test提供了`@SpyBean`和`@MockBean`，应该很好写测试用例

**Comment by linux-china** [comment]
这个我还不能确定，我们可以先等一下Spring 6的Make RSocket call interface的实现，然后看一下官方的推荐是如何做的。目前的HTTP interface还是基于标准interface的，并没有采用@FeignClient这样的实现。
https://docs.spring.io/spring-framework/docs/6.0.0-M5/reference/html/integration.html#rest-http-interface

> 我感觉注解声明式风格肯定要比写一堆boilerplate code好

这个我不太确定，之前大家都是使用Spring XML声明的，现在基本上都是Auto Configuration代码的。 至于代码是否是boilerplate code，这个要看团队如何处理的，同样的YAML也是boilerplate code，每一个项目都需要添加这个YAML配置。

还有一个问题就是，如果大量使用注解和扫描特性，这个在GraalVM native-image上处理也比较麻烦，还要单独为native-image做处理。

考虑大家习惯，可以考虑创建一个新的rsocket-auto-client项目，实现这样的需求。

**Comment by CoderYellow** [comment]
可以的，dubbo受众也比较广，但那个context应该不是数组了

**Comment by linux-china** [comment]
@CoderYellow  RSocket Interface已经推出啦，详情请参考：  https://docs.spring.io/spring-framework/docs/6.0.0-SNAPSHOT/reference/html/web-reactive.html#rsocket-interface

如果可能的话，个人觉得直接interface直接使用 @RSocketExchange 可能是一个不错的选择，这个和Spring也是兼容的，不需要再重新创建一个新的Annotation，也能做到和Spring RSocket互通。

**Comment by linux-china** [comment]
@CoderYellow  RSocket Interface  https://docs.spring.io/spring-framework/docs/6.0.0-M6/reference/html/web-reactive.html#rsocket-interface    可以考虑直接使用 @RSocketExchange
