### ISSUE TITLE
建议添加多种不同类型的example来引导新手入门

### ISSUE THREAD

**Issue by veione** [alibaba/alibaba-rsocket-broker#210]
建议添加多种不同类型的example来引导新手入门，现阶段rsocket的相关知识太少了，目前提供的只有request-response模式，跑完之后还是不知道如何下手。比如我想拿rsocket-alibaba的request-channel模式来做个简单聊天功能，需要处理单人，多人，广播，这些如果用netty只需要保留对应的channel即可，如果更换rsocket又需要如何去实现呢

**Comment by linux-china** [comment]
目前RSocket Broker主要集中在服务之间的通讯，如果是聊天的场景的话，可能使用Spring RSocket比较方便。 欢迎这里讨论  https://github.com/alibaba/alibaba-rsocket-broker/discussions/196
