### ISSUE TITLE
一个RSocket-Broker使用者的想法

### ISSUE THREAD

**Issue by cuihe500** [alibaba/alibaba-rsocket-broker#213]
我是国内普通本科的一名大三学生，接触并且使用本项目大概有10个月左右的时间了。今天看到一个RP，关于本项目迭代问题的，所以有些话想说一下。因为自己水平和接触到的项目太少，很多想法都是比较不成熟甚至是幼稚的。希望各位大佬能够指正我。
我现在主导的是一个教育平台的开发。主要使用的是Java语言和RSocket协议。起初的选型就是SpringCloud(Nacos,OpenFegin)等等，但是我部署的机器太差了，都是一些很早之前学校退休下来的pc机。使用K8s管理，跑起来后，动不动就宕机，雪崩，于是就找方案，最好是一种性能高、占用小、能够异步的框架。查资料的时候，找到了RSocket协议，并且找到了本项目。
目前我主导开发的教育平台，已经在校内推出了第一个正式版本，为大概4000人左右提供了服务。并且包含了虚拟实验、人工智能等框架一起提供，使用K8S管理。
所以我个人觉得，RSocket协议，RSocketBroker(本项目)是一个非常棒，非常有意义的项目。今天才了解到，本项目是由大佬一个人贡献的。感谢大佬 @linux-china  对该项目的贡献，为我们提供了如此棒的一个服务。我也一直在研读和学习本项目的代码，并且做了一些改动（由于都是为了更加贴合我主导的项目，所以没有提PR）。
@linux-china 由于我能力有限，可能没办法作为一个本项目合格的开发者，但是我非常想为咱们的项目提供自己的贡献。大佬的这种开源精神和坚持不懈的努力让我真的受益匪浅，所以如果有可能的话，我会尽自己可能，为本项目修复一些BUG并且提交一些新特性代码！
其实在我实际使用之中，我觉得本项目还是很有发展前景的。可以继续去贴合云原生，提供一些Native的特性等等。这些只是本人个人的想法和建议，若有问题，麻烦各位随时指正！万分感谢！！

**Comment by linux-china** [comment]
> 并且做了一些改动（由于都是为了更加贴合我主导的项目，所以没有提PR）。

不用担心自己的能力差(每一个人都是从初级程序员过来的)，如果你觉得改动点非常必要，你可以提一个issue，然后共同讨论一下，这个讨论还是非常有意义的。

**Comment by cuihe500** [comment]
> > 并且做了一些改动（由于都是为了更加贴合我主导的项目，所以没有提PR）。
> 
> > And made a few changes (because all is to be in order to fit the project that I lead more, did not mention PR so).
> 
> 不用担心自己的能力差(每一个人都是从初级程序员过来的)，如果你觉得改动点非常必要，你可以提一个issue，然后共同讨论一下，这个讨论还是非常有意义的。
> 
> Don't worry about your ability (everyone comes from junior programmers). If you think the change is necessary, you can raise an issue and discuss it together. This discussion is still very meaningful.

感谢您的鼓励，这对我真的会非常有用！我会尽自己所能的去为本项目提供贡献，努力成为一个更好的程序员！:)
为了不打扰项目的正常issue，我先将这个问题关闭！
