### ISSUE TITLE
数据大小的限制

### ISSUE THREAD

**Issue by hupeiD** [alibaba/alibaba-rsocket-broker#214]
查看源码，在连接至Broker的时候生成的RSocketConnecter无法对frameLength或mtu做配置，使用http-gateway的时候如果需要透传超过16MB的文件时该怎么处理呢？是否加个Configurer增加对RSocketConnector的拓展比较好呢，或者UpstreamManager增加个参数配置？

**Comment by linux-china** [comment]
@hupeiD  从架构上来说，如果文件超过16M的话，最好使用一个文件存储服务，如AWS S3， 阿里云OSS等，然后在消息中传递文件对应的唯一ID就可以。 如果消息过大，在网络上经过N次传输，这个非常影响性能，尤其是事件和消息类型，还涉及到消息的解析等。 很多消息系统也有这样的限制，如消息不能超过512K或者2M等。
