### ISSUE TITLE
java 17   支持

### ISSUE THREAD

**Issue by sdack-cloud** [alibaba/alibaba-rsocket-broker#215]
升级了spring boot 3.0 出现了错误

```
Parameter 0 of method abcService in ServicesAutoConfiguration required a bean of type 'com.alibaba.rsocket.upstream.UpstreamManager' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'com.alibaba.rsocket.upstream.UpstreamManager' in your configuration.
```

**Comment by cuihe500** [comment]
我也出现了这个问题 正在想办法解决。目前正在考虑注入优先级问题。

**Comment by sdack-cloud** [comment]
@linux-china

**Comment by linux-china** [comment]
@sdack-cloud  spring.factories 的调整啦，需要添加新的配置方式  https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.developing-auto-configuration     这个我稍后添加一下

**Comment by sdack-cloud** [comment]
<img width="974" alt="截屏2022-12-03 08 58 52" src="https://user-images.githubusercontent.com/49465225/205414690-40a5797c-99fe-4362-9a8e-0b50cfa3e8c8.png">

![image](https://user-images.githubusercontent.com/49465225/205414724-f2806752-047d-4c9c-9993-c64660933be3.png)
遇到些问题

docker 镜像也更新哦

**Comment by linux-china** [comment]
Spring Boot 3的兼容主要是Alibaba RSocket对应的开发包，而不是Alibaba RSocket Broker Server本身，目前Alibaba RSocket Broker还不能升级到Spring Boot 3，主要是控制台界面使用Vaadin开发，这个还没有做到Spring Boot 3的兼容，这个要等一下Vaadin进行升级。 但是RSocket Broker就是一个独立的服务应用，不影响你的其他Spring Boot 3的应用接入。 

你这个编译问题，你自己排查一下。 Alibaba RSocket Broker的GitHub Actions的持续集成都是没有问题的 https://github.com/alibaba/alibaba-rsocket-broker/actions

**Comment by linux-china** [comment]
一个样例：  https://github.com/alibaba-rsocket-broker/alibaba-rsocket-boot3-demo

**Comment by sdack-cloud** [comment]
[/alibaba-rsocket-boot3-demo](https://github.com/alibaba-rsocket-broker/alibaba-rsocket-boot3-demo)

<img width="1241" alt="截屏2022-12-05 09 41 42" src="https://user-images.githubusercontent.com/49465225/205531042-682f18c2-5e6e-4db1-be1e-fc227e71e9de.png">

**Comment by linux-china** [comment]
@sdack-cloud  这个是snapshot版本，你要本地编译安装一下，这个是Java程序员最基本的要求 ;) 

```
# install artifact into local repository
artifacts-install:
  mvn -pl .,alibaba-rsocket-service-common,alibaba-rsocket-core,alibaba-rsocket-spring-boot-starter,alibaba-broker-spring-boot-starter -DskipTests clean source:jar install

```

**Comment by sdack-cloud** [comment]
Running with Spring Boot v3.0.0, Spring v6.0.2
正常启动

**Comment by linux-china** [comment]
1.1.4已经发布，兼容Spring Boot 3.0.0
