### ISSUE TITLE
通过 RSocketConfigPropertySourceLocator 获取的配置信息字符串，一头一尾各多一个双引号

### ISSUE THREAD

**Issue by songshuohua** [alibaba/alibaba-rsocket-broker#231]
**Describe the bug**
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/8054308/232996298-bd90928c-9629-4962-be57-4df3d4065373.png">

@linux-china 大佬，应用启动时，RSocketConfigPropertySourceLocator 使用 http 访问 broker 获取配置信息。但得到的配置信息字符串，总是比实际的字符串多了两个双引号（一头一尾）。通过 ConfigurationEventProcessor 获取的 ConfigEvent 中的配置信息字符串，就没这个问题，并无多余双引号。关于 Config Server，我使用的是你提供的版本 https://github.com/alibaba-rsocket-broker/rsocket-broker-config-server-service  能否麻烦确认下，谢谢！

该项目提供了 ### Environment

* Alibaba RSocket Broker version: 1.1.4
* Operating System version: Mac
* Java version: 11.0.7

**Comment by linux-china** [comment]
确实有这个问题，这个主要是在字符串JSON序列化时添加上的，先做了替换处理。 我再看一下其他地方是否有类似的问题。 感谢反馈 :)
