### ISSUE TITLE
现在能作为api网关直接用nginx 访问broker请求业务吗 

### ISSUE THREAD

**Issue by xufengzz** [alibaba/alibaba-rsocket-broker#237]
我没看到相应示例应该如何与现有的spring gateway业务整合。还有未来的计划是什么呢。有没有想法接入k8s网关api   实现云原生的api网关

**Comment by xufengzz** [comment]
看到了这个示例。但是要用包名作为请求路径。好怪啊。有法配置映射吗 做个管理界面。
![image](https://github.com/alibaba/alibaba-rsocket-broker/assets/43258342/deea101f-64a6-4ac2-ad41-2535dbc1d923)

**Comment by shareisall** [comment]
你可以看下 broker server 的 api 控制器，那里有你想要的。这不是包名，是完整服务接口名（如果你把所有的服务接口都放在某个地方，那你就在控制器里边把报名预置好，再和服务接口拼接）。

**Comment by xufengzz** [comment]
> 你可以看下 broker server 的 api 控制器，那里有你想要的。这不是包名，是完整的服务名。若你把所有的服务都放在某个包下，那你就在 api 控制器里边把包名预置好，再和服务名拼接后传入即可。项目里边的 broker server 只是个演示程序。

懂了。意思项目里的这个只是基本演示。我集成starter包  扩展一下 api 网关入口就行了。后端管理系统也可以自己开发。
现在这个服务名已经注册到网关的路由表了。在管理系统加个路由配置功能就行了。
