### ISSUE TITLE
RSocket Payload自定数据类型支持

### ISSUE THREAD

**Issue by linux-china** [alibaba/alibaba-rsocket-broker#25]
在RSocket Broker的场景中，一个RSocket长连接会传输各种类型的Payload，虽然RSocket长连接支持全局的Payload的data mime type，但是实际中会存在不用的业务场景使用不同的数据编码格式，如RPC调用和Kafka消息可能就是不同的数据类型，这个时候就需要给每一个Payload设置独立的数据编码格式，对于RPC场景，可能还存在对返回数据的数据编码需求，如以下签名：

```
User findUserByNick(String nick);
```

有可能是请求的时候是Text/Plain编码，而返回的对象结果要求是JSON编码，这种不同的编码需求主要是出于个性化和性能要求。  在RSocket 281的Metadata规范中，增加了data encoding和accept data encoding两者元数据类型，这样可以保证满足该场景的要求。  

在RSocket Broker中，建议服务提供方支持多种数据类型，目前主要包括：

* 数字类型编码支持： 如果Integer, long, double等
* 字符串支持: String
* byte数组: 如在文件上传的场景
* 自定义序列化方式:  JSON, Hessian, Protobuf, Avor这四者

Composite Metadata Extension: data Mime/type definition per-stream： https://github.com/rsocket/rsocket/issues/281

**Comment by linux-china** [comment]
已经增加了 MessageMimeTypeMetadata  和 MessageAcceptMimeTypesMetadata，同时服务端也会根据传入的数据类型进行调整。目前的样例就是RSocket HTTP Gateway使用json。

**Comment by tomasz-galuszka** [comment]
What about a case when in the SETUP frame do an authentication with metadata mime type: message/x.rsocket.authentication.v0. After the successful authentication then send some FNF requests with metadataMimeType: message/x.rsocket.routing.v0 - to different logical endpoints.

SETUP: https://github.com/rsocket/rsocket/blob/5920ed374d008abb712cb1fd7c9d91778b2f4a68/Extensions/Security/Authentication.md

REQUEST_FNF: https://github.com/rsocket/rsocket/blob/5920ed374d008abb712cb1fd7c9d91778b2f4a68/Extensions/Routing.md

I guess with the fixed metadata mimetype currently it is not possible. The only way I could achieve that is to use composite metadata with only one item inside, but with different mime types (but I feel it is a bit over-kill).
