### ISSUE TITLE
服务路由性能提升

### ISSUE THREAD

**Issue by linux-china** [alibaba/alibaba-rsocket-broker#3]
目前路由的算法是 group + service name + version，然后对其进行hashcode，然后在进行bitmap匹配查找。 可以考虑在调用方提前将路由信息进行HashCode化，然后基于Integer Hashcode进行bitmap匹配，这样只需要读取composite metadata的前8个字节(1 + 3 + 4)就可以完成路由匹配。 考虑到Hashcode各个语言的一致性性，还是采用 MurmurHash3 算法。

**Comment by tanhaipeng** [comment]
内部的broker终于开源了👍

**Comment by linux-china** [comment]
Routing的逻辑已经调整为如下格式：

```
group:service_full_name:version
m=method_name
```

如果后续基于路由做hashcode化，只需要hash第一个路由key就可以啦。

**Comment by linux-china** [comment]
如果路由metadata(message/x.rsocket.routing.v0) 位于第一位，那么 payload的metadata的前几个格式如下：

* 1 byte for routing mimetype, 
* 3 bytes for routing metadata length, 
* 1 byte for routing key Tag Length
* N bytes for routing key text

如果N为4bytes，我们可以理解为一个Integer值，这里的限制条件就是routing key必须大于4bytes。

**Comment by linux-china** [comment]
https://github.com/alibaba/alibaba-rsocket-broker/wiki/RSocket-Routing
