### ISSUE TITLE
Tracing Metadata Extension Adapters

### ISSUE THREAD

**Issue by linux-china** [alibaba/alibaba-rsocket-broker#33]
目前tracing的产品比较多，AP和规范也各自不同，考虑能在Broker上适配主流的Tracing产品。

* Brave(Zipkin): https://zipkin.io/
* OpenTracing: https://opentracing.io/   
* OpenCensus: https://opencensus.io/
* OpenTelemetry:  https://opentelemetry.io/

Bridge between OpenTracing and Brave: https://github.com/openzipkin-contrib/brave-opentracing

**Comment by linux-china** [comment]
RSocket已经支持Zipkin Tracing Metadata， https://github.com/rsocket/rsocket/blob/master/Extensions/Tracing-Zipkin.md   这个可能需要一定的转换。

**Comment by cafechen** [comment]
RSocket-Broker是否上过一些生产环境？
怎么为RSocket-Broker做贡献？

**Comment by linux-china** [comment]
Alibaba内部已经在用啦。 https://dzone.com/articles/rsocket-broker-use-case-in-alibaba-cloud   
贡献很简单，在这个库提交 bug、需求、疑问、code review、wiki文档等都可以，没有任何限制。 如果你有和RSocket相关的Demo，新建一个issue，说明你的demo，添加你的github连接， 我们会专门做一个页面将broker关联Demo都添加上。  @cafechen

**Comment by cafechen** [comment]
适配Zipkin这个工作如果不着急，我可以试试完成么？

**Comment by linux-china** [comment]
@cafechen  感谢。   Zipkin Server with RSocket Collector代码在这里  https://github.com/linux-china/zipkin-rsocket-server     Zipkin Sender RSocket  代码这里   https://github.com/linux-china/zipkin-sender-rsocket   感谢review。

**Comment by linux-china** [comment]
@cafechen  zipkin的整合已经完成啦，可能还与一些细节要处理。 目前是基于zipkin brave做的。网络上是rsocket的trace metadata。
