### ISSUE TITLE
咨询：rsocket-broker互联网企业使用场景？

### ISSUE THREAD

**Issue by andyyin** [alibaba/alibaba-rsocket-broker#49]
看readme.md中的介绍，解决了“传统设计中众多的问题”，但是当前这些问题都有成熟的方案。
不太了解rsocket-broker在阿里目前都有哪些方面的实际应用？

**Comment by linux-china** [comment]
关于RSocket适用的场景，RSocket by Example http://rsocketbyexample.info/  有一些介绍，如果没有涉及到的，这里反馈一下。 目前内部使用场景主要是FaaS。

**Comment by andyyin** [comment]
OK，了解了，谢谢。之前有了解过阿里的faas，请求都走broker中转。
