### ISSUE TITLE
希望可以建立高效的沟通组织

### ISSUE THREAD

**Issue by A-CiKe** [alibaba/alibaba-rsocket-broker#50]
希望建立钉钉或者QQ群之类的沟通群组，方便大家遇到问题及时沟通。

**Comment by linux-china** [comment]
有几个微信群，但是通常不希望打扰大家，每一个人的问题可能不太一样。 如果大家有什么问题，可以考虑加入 Gitter， https://gitter.im/alibaba-rsocket-broker/community

**Comment by linux-china** [comment]
GitHub Discussions可用时，会很快启动项目级别的 GitHub Discussions
