### ISSUE TITLE
MESSAGE_RSOCKET_BINARY_ROUTING 等在项目中的io.rsocket.metadata.WellKnownMimeType类中，在Rsocket-core-1.0.0.jar中存在同名类，导致加载时报找不到Field。

### ISSUE THREAD

**Issue by bxvs888** [alibaba/alibaba-rsocket-broker#58]
MESSAGE_RSOCKET_BINARY_ROUTING 等在项目中的io.rsocket.metadata.WellKnownMimeType类中，在Rsocket-core-1.0.0.jar中存在同名类，导致加载时报找不到Field。
经过排查，classloader加载了Rsocket-core-1.0.0.jar 这个里面的WellKnownMimeType报找不到Field。

**Comment by linux-china** [comment]
这个是为了考虑厂商自定义特定字段的问题。 能告知一下什么情况下导致的问题吗？  能描述你一下你的场景或者测试的项目代码吗？ 如果有代码在github上最好，谢谢。

**Comment by linux-china** [comment]
@bxvs888  我查的问题不是这个，能否告知一下你使用的场景和版本吗？  唯一这个同名class，主要是方便第三方进行扩展，官方SDK未必能覆盖到公司内部的一些序列化的方式。

**Comment by bxvs888** [comment]
IntelliJ IDEA 2020.1 ,dragonwell_11.0.7.2.jdk  macOS 10.15 操作系统，14号 Master版本。正在测试有内部RPC使用这个的可行性。

**Comment by linux-china** [comment]
已经提交了啦，主要是classpath排序的问题，已经将alibaba-rsocket-core提到dependency依赖的第一位，请使用最新的master测试一下。  如果还有这个问题，也欢迎反馈一下。 请确保classpath中，alibaba-rsocket-core-1.0.0.M2.jar在rsocket-core-1.0.0.jar之前出现。  为也会测试一下 dragonwell_11 的JDK版本。

**Comment by shpodg** [comment]
broker内部项目对依赖排序并不是一个稳定的解决方案，因为在我的测试中，当把有依赖`rsocket-core`的类库（比如`spring-boot-starter-rsocket`）放到`alibaba-rsocket-spring-boot-starter`前面的时候还会出现类似问题。

第二个问题是不同的jar包拥有相同的包路径以后在java9模块化也会有问题
https://www.logicbig.com/tutorials/core-java-tutorial/modules/split-packages.html
