### ISSUE TITLE
使用Java 14编写RSocket Broker Server & Gateway

### ISSUE THREAD

**Issue by linux-china** [alibaba/alibaba-rsocket-broker#59]
想问一下大家，准备将一下Broker Server和Gateway调整为Java 14编写和运行，而提供给应用集成的开发包还是Java 8编写，这样主要是可以利用Java新特性，代码更精简且开发效率高，同时让代码后续更好维护一些，当然还有JVM本身的性能提升。 

想问一下大家实际开发中都使用哪些Java版本。

**Comment by m1ngyuan** [comment]
现在80%的系统环境都运行在Java 8上面，我认为不适合直接使用Java 14;
但是如果某些特性依赖特定的JDK的，倒可以考虑提供适用各种JDK的类库，你觉得呢

**Comment by linux-china** [comment]
@m1ngyuan  只有server采用jdk 14编写，而alibaba-rsoket-core, service-common这些还是java 8的。 在不同的module要进行Java 8和Java 14间切换，开发协调有点麻烦。

**Comment by FlatMapIO** [comment]
直接用 Kotlin 吧，比用 java14 产生的成本小。

**Comment by PeterXiao** [comment]
Kotlin currently do not have any specific features for bytecode newer than 1.8. In future, there surely be new features, but right now, it is OK to set the bytecode target to 1.8 and enjoy any JDK.

**Comment by qiyuey** [comment]
Kotlin +1

**Comment by weir2010** [comment]
有点超前，不过对于这个项目来说不算超前

**Comment by linux-china** [comment]
已经很久啦，看来只能上 17 啦  :)

**Comment by kevinten10** [comment]
同意17 LTS。按目前的预告来看，17将会是里程碑式的版本 https://www.infoq.cn/article/rqfww2r2zpyqiolc1wbe

**Comment by pc859107393** [comment]
首先来说，目前java生态里面还是8的更加健全，虽然说不是最好，但是共识的东西能让大家更加乐于接受。如果说还需要考虑性能提高，可以考虑配套的netty优化、jvm优化或者说添加graalvm支持。另外kotlin重写也是个不错的方向。 当然这些埋点都可以为以后的14版本做准备，就像 rsocket代理类用jdk实现一样。 积极的社区讨论和技术埋点，到关键时刻爆发，这样更能提升整体项目的影响力。

**Comment by FlatMapIO** [comment]
rsocket-kotlin  已经用多平台实现浏览器和服务器共享代码通信的样例了， 这种项目跨端同构非常重要。

**Comment by linux-china** [comment]
关闭啦，已经是Java 17啦，接下来就是Java 17开发broker啦 :)
