### ISSUE TITLE
建议 Server 应用转换为 Webflux Style

### ISSUE THREAD

**Issue by FlatMapIO** [alibaba/alibaba-rsocket-broker#65]
**Is your feature request related to a problem? Please describe.**

@Controller 风格的编程范式有利于老应用兼容, 但有比较厚重的 Runtime , 在 WebFlux 环境中建议用 RouterFunction & Functional 方案

**Describe the solution you'd like**

使用 RouterFunction 定义 Handler 

**Describe alternatives you've considered**

No

**Additional context**
> Difference between @Controller and RouterFunction in Spring 5 WebFlux
> https://stackoverflow.com/a/62010641/2176244

**Comment by linux-china** [comment]
目前有一个问题，就是要支持Vaadin，而Vaadin当前不支持Spring webFlux，这个要稍等一下Vaadin的调整。目前web的功能主要是构建 vaadin UI和提供一些REST API。
