### ISSUE TITLE
求MQTT协议、XMPP协议到RScoket协议转换的gateway

### ISSUE THREAD

**Issue by YuanHuCoding** [alibaba/alibaba-rsocket-broker#67]
求MQTT协议、XMPP协议到RScoket协议转换的gateway。
咱们做的这些协议转换，很类似EMQ X Edge做的事情吧。
EMQ X Edge：轻量级多协议物联网边缘消息中间件，支持部署在资源受限的物联网边缘硬件。支持MQTT, CoAP, HTTP 以及 Modbus 各种工业协议。

**Comment by YuanHuCoding** [comment]
顺便问一下http://rsocketbyexample.com上的图是用什么软件画的？

**Comment by linux-china** [comment]
> 顺便问一下[http://rsocketbyexample.com上的图是用什么软件画的？](http://rsocketbyexample.com%E4%B8%8A%E7%9A%84%E5%9B%BE%E6%98%AF%E7%94%A8%E4%BB%80%E4%B9%88%E8%BD%AF%E4%BB%B6%E7%94%BB%E7%9A%84%EF%BC%9F)

使用PlantUML画的。 rsocketbyexample.com 的源码都在这里 https://github.com/linux-china/rsocketbyexample/tree/master/diagrams

**Comment by linux-china** [comment]
> 求MQTT协议、XMPP协议到RScoket协议转换的gateway。
> 咱们做的这些协议转换，很类似EMQ X Edge做的事情吧。
> EMQ X Edge：轻量级多协议物联网边缘消息中间件，支持部署在资源受限的物联网边缘硬件。支持MQTT, CoAP, HTTP 以及 Modbus 各种工业协议。

我抓紧把MQTT的转换发布一下。 另外我看一下，能否让EMQ X Edge能对接RSocket支持。

**Comment by weimianlong** [comment]
同求。。。不想搞EMQ的erlang，招不到人。。。如果性能、稳定、扩展都不错，mqtt broker准备切到rsocket。

**Comment by linux-china** [comment]
更新一下， Netty 4.1.52增加了MQTT 5的支持。 https://netty.io/news/2020/09/08/4-1-52-Final.html

**Comment by YuanHuCoding** [comment]
MQTT协议到RScoket协议转换的gateway好像还没有哦。

**Comment by linux-china** [comment]
rsocket-broker-gateway-mqtt 这个简单的MQTT Gateway，主要特性是Reactive的支持，当然也可以对接各种Reactive框架，如RSocket， Reactor Kafka。 个人对MQTT了解有限，希望大家能一起贡献，我这个算Alpha版本，给大家提供一些思路。  https://github.com/alibaba-rsocket-broker/rsocket-broker-gateway-mqtt
