### ISSUE TITLE
如何看待官方的 rsocket-routing-broker

### ISSUE THREAD

**Issue by timy880093** [alibaba/alibaba-rsocket-broker#70]
如題，官方的 https://github.com/spring-cloud-incubator/spring-cloud-rsocket 已經 Archived
以後核心會改成這個嗎 https://github.com/rsocket-routing/rsocket-routing

**Comment by linux-china** [comment]
这个是Spencer在领导开发的。  我们都知道的，Spring会给出产品的思想和原型，如我们了解的Spring Cloud Config Server, Spring Cloud Registry Server, Spring Cloud gateway等等，这些产品主要基于Spring Cloud规范的参考实现，也方便其他第三方产品方便接入到Spring Cloud规范上，如我们会看到Spring Config Server有ZooKeeper， Consul等实现。 Spring推出的产品并不是产品化非常高的产品，你还需要进行二次开发，如控制台、规则定制等。   

RSocket Routing也是类似的思想，主要是让更多开发者参与到RSocket开发上，而且各个RSocket Broker的路由规范和架构设计都有不同，主要是瞄准不同的业务场景，而不是RSocket Routing把其他的产品全部干掉。

我建议有兴趣的同学可以看一下，主要是路由规范和集群管理的差别，最后你可以根据你实际的业务情况进行选择，就和其他的Spring Cloud产品一样，如一个config server都有好几个产品实现。

**Comment by linux-china** [comment]
Spencer在Twitter上说明很快会发布MileStone的RoadMap，感兴趣的同学可以看一下  https://github.com/orgs/rsocket-routing/projects/1  这上面的计划。 另外也可关注一下  https://github.com/rsocket-routing/rsocket-routing-broker

**Comment by linux-china** [comment]
Spence在SpringOne 2020大会上的架构图，应该非常清晰： 
![image](https://user-images.githubusercontent.com/46711/92130965-38bf9100-edba-11ea-90aa-96844a46b973.png)

对比Alibaba RSocket Broker，Spring RSocket Broker是有集群内部的转发的，这个要看具体的业务场景，如性能等，这个要看具体的业务场景。
