### ISSUE TITLE
rsocket-broker可以跨idc部署吗

### ISSUE THREAD

**Issue by jiangyanming** [alibaba/alibaba-rsocket-broker#75]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when
rsocket-broker可以跨idc部署吗，如果可以，异常情况导致分区后，流量如何处理
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by linux-china** [comment]
broker是支持多集群的。 
* 不同IDC不用集群(Different IDC with different rsocket broker cluster): https://github.com/alibaba/alibaba-rsocket-broker/wiki/RSocket-Broker-Clusters
* 中心化集群(One central cluster for all apps from different IDC):  http://rsocketbyexample.info/hybrid-cloud-vendors/index.html

关于流量分配，在方案一中是就近原则，也就是本集群中有服务，就会优先选择本集群的。 当然RSocket Broker提供Filter机制，你可以自行扩展对应的流量策略。
