### ISSUE TITLE
现在需要搭建文档&官网么？

### ISSUE THREAD

**Issue by lisirrx** [alibaba/alibaba-rsocket-broker#8]
https://github.com/txd-team/docsite 
看了下dubbo、nacos都是直接用docsite搭建的官网，我们需不需要现在开始也搞一下呢？

**Comment by linux-china** [comment]
有同学对比过 hugo 吗？  https://gohugo.io/

**Comment by AhianZhang** [comment]
> 有同学对比过 hugo 吗？ https://gohugo.io/

简单整理了一下，如果阿里内部不要求风格统一的话推荐用 hugo  (:

|| **[docsite](https://github.com/txd-team/docsite)**  | **[hugo](https://github.com/gohugoio/hugo)**   |
 |:---: | :---: | :---: |
|最近一次更新| 三个月前  | 八天前  |
|主要开发语言| javascript  | golang  |
|风格|贴近于中国用户|适合国际化|
|命令行支持|初始化、本地预览、部署|初始化、更换主题、创建文章、本地预览、部署|
|用户举例|[dubbo](https://dubbo.incubator.apache.org/en-us/),[nacos](https://nacos.io/en-us/),[TX-LCN](http://www.txlcn.org/zh-cn/)| [letsencrypt.org](https://letsencrypt.org/)，[support.1password.com](https://support.1password.com/)，[linode.com](https://linode.com/docs/)|

**Comment by linux-china** [comment]
更新一下： 目前打算采用Hugo  + Docsy构建站点，大家有什么建议吗？

**Comment by linux-china** [comment]
更新一下： 目前RSocket by Example已经上线  http://rsocketbyexample.info

**Comment by linux-china** [comment]
和 https://rsocket.io 的技术一致，采用Facebook的 Docusaurus https://docusaurus.io/  构建站点，很快很大家见面。

**Comment by linux-china** [comment]
https://alibroker.info/  上线啦 :)
