### ISSUE TITLE
自定义服务名后，无法正常调用服务

### ISSUE THREAD

**Issue by HuangDongdong666** [alibaba/alibaba-rsocket-broker#83]
### 自定义服务名后，无法正常调用服务  
---
测试的时候发现了一个小问题，自定义服务名后，无法正常调用服务.
---
Version :  Alibaba RSocket Broker version: 1.0.0-RC2
---
问题复现：
1.修改example模块的rsocket-responder的UserServiceImpl类

````
@RSocketService(serviceInterface = UserService.class,name = "com.alibaba.UserService")
@Service
public class UserServiceImpl implements UserService {
...
}
````

2.使用postman测试
* http://localhost:9998/api/com.alibaba.UserService/findById（修改后服务名）  
 提示服务不存在（正常提示，无异常）
````
RST-900404: Service not found com.alibaba.UserService
````
 * http://localhost:9998/api/com.alibaba.user.UserService/findById （服务接口全限定名）
 抛出异常，No service handler found: com.alibaba.user.UserService.findById
````
 [  XNIO-1 task-1] io.undertow.request                      : UT005023: Exception handling request to /api/com.alibaba.user.UserService/findById
````
----
操作依据：
wiki的服务接口设计
https://github.com/alibaba/alibaba-rsocket-broker/wiki/RSocket-Service-Interface-Design#interface-service

![image](https://user-images.githubusercontent.com/34422862/94659045-470bb900-0336-11eb-84a0-c59f310c0ca7.png)

---
请看看是文档没更新呢，还是那里操作不对，或者是真的有问题呢...

**Comment by linux-china** [comment]
这个是在服务注册时使用了interface作为服务名称啦，已经修复这个bug啦，非常不好意思，我准备下一个版本发布。

**Comment by linux-china** [comment]
如果遇到这个问题，可以打开控制台 http://localhost:9998/ 查看services 列表，有服务全称列表。 在服务注册的时候，忽略了自定service name
