### ISSUE TITLE
其他语言开发的RSOCKET服务，如何注册到boker？

### ISSUE THREAD

**Issue by yangjungis** [alibaba/alibaba-rsocket-broker#87]
**期望提供其他语言通过broker注册和发现的示例代码**

建议封装多语言的SDK

**Comment by linux-china** [comment]
这个确实需要，我整理一下。 原理上也非常简单，就是添加一些RSocket metadata信息，我会添加一下各种语言对应的Demo，方便大家对接broker。

**Comment by yangjungis** [comment]
有没有对接技术资料，我打算用rust写一个测试

**Comment by linux-china** [comment]
代码这里 https://github.com/alibaba/alibaba-rsocket-broker/blob/master/alibaba-rsocket-core/src/test/jbang/RSocketBrokerClient.java

**Comment by yangjungis** [comment]
https://github.com/alibaba/alibaba-rsocket-broker/blob/master/example/rsocket-responder/src/test/java/com/alibaba/spring/boot/rsocket/demo/RawRSocketTest.java 单元测试没有看到如何注册1个自己编写的rsocket服务到broker.

**Comment by linux-china** [comment]
连接到broker其实就是注册啦，然后应用就可以调用RSocket服务啦。 如果你要发布服务，其实就是向broker发送一个暴露服务的cloudevent事件，标明你能提供什么服务。  参考最新的代码 https://github.com/alibaba/alibaba-rsocket-broker/blob/master/alibaba-rsocket-core/src/test/jbang/RSocketBrokerClientApp.java

**Comment by yangjungis** [comment]
1.0.0.RC3 还没有 client 这个包
