### ISSUE TITLE
增加对 capnproto 协议的支持

### ISSUE THREAD

**Issue by yangjungis** [alibaba/alibaba-rsocket-broker#88]
增加对 capnproto 协议的支持

https://capnproto.org/

**Comment by linux-china** [comment]
这个可以考虑通过第三方扩展的方式添加进来。 只需要implements ObjectEncodingHandler接口，实现Cap’n Proto对应的扩展，如 ObjectEncodingHandler CapnProtoImpl，然后设置一下Service Loader配置就可以。

**Comment by linux-china** [comment]
RSocket协议已经添加了capnproto的协议支持。 https://github.com/rsocket/rsocket/blob/master/Extensions/WellKnownMimeTypes.md   alibaba rsocket broker也添加了对应的well known type，这样你可以一个byte就可以表示该类型，效率高非常多。 你可以自行扩展一个capnproto的支持，也不太麻烦。考虑到这两者并不普遍，所以rsocket broker就不考虑直接支持，你可以考虑扩展一下。 如果有问题，可将代码仓库发一下，可以协助调试一下。 

当时不用担心，虽然是需要自行扩展的，但是只有在requuester和reponder两边需要，对应broker来说，并不影响，主要是broker不解析payload的data。
