### ISSUE TITLE
自定义负载均衡器和路由

### ISSUE THREAD

**Issue by hupeiD** [alibaba/alibaba-rsocket-broker#91]
如果想自定义负载均衡策略或路由，如想要通过实时收集服务提供者或服务消费者的某些业务数据来调整负载或路由的时候，在实现上显得有些吃力。目前的设想是，通过过滤器来更新 源、业务数据以及目标之间的映射关系，并通过CloudEvent来加载或卸载对应的映射关系，但实现起来显得十分的不优雅。也可能是我没有完全掌握框架的用法，如果有其他的建议，方便的话请告知一下。

如果这个功能会被考虑添加在将来的版本的话，仅为抛砖引玉，提供两个思路以供参考：
1、在Broker端是否可以添加允许自定义规则的，用于实时收集的数据的端点，并且附带上GSVRoutingMetadata和AppMetadata信息便于在Broker端进行处理。
2、在Service中，允许直接接收RSocketExchange，即使得GSVRoutingMetadata和AppMetadata直接穿透到业务处理中。但可能需要考虑的时，在接收时可能并非需要RSocketExchange的全量数据，全量传输的话可能会带来数据传输上的不必要的开销。或者该用法仅局限在Broker端使用。其次，按照现在Service接口的设计，直接调用Service上传信息似乎不太可行，需要另外构思接口如何调用。

**Comment by linux-china** [comment]
在RSocket  Broker中，你可以使用Filter机制来做，你可以参考 CanaryFilter  https://github.com/alibaba/alibaba-rsocket-broker/blob/master/alibaba-broker-server/src/main/java/com/alibaba/rsocket/broker/filters/CanaryFilter.java   

在run() 方法中，你可以根据业务逻辑调整 GSVRoutingMetadata 对象的属性，如endpoint，targetId（目标handler），然后调整对应的路由规则。

**Comment by hupeiD** [comment]
嗯，现在是这么处理的。

然后我用BinaryRoutingMetadata时，发现在RSocketBrokerResponderHandler解析时，如果不携带routingText的，解析会报空指针。routingText本就不是必填的话，那这里其实并不一定需要将GSVRoutingMetadata解析出来对吧。如果必须的话，判空后从LocalReactiveServiceCaller中取出是不是也可以。

```java
    ...
    if (binaryRoutingMetadata != null) {
        // 这里
        gsvRoutingMetadata = GSVRoutingMetadata.from(new String(binaryRoutingMetadata.getRoutingText(), StandardCharsets.UTF_8));
        serviceId = binaryRoutingMetadata.getServiceId();
        encodingMetadataIncluded = true;
    }
    ...
```

**Comment by linux-china** [comment]
是的，如果有binaryRoutingMetadata是不需要的，但是考虑到一些filter是基于gsv的，还有method等信息，目前的binary routing设计还是考虑了解析添加额外元信息方便filter编写，还有metrics等。 如果你们内部没有这些需求，完全可以根据binary进行路由，这样性能最高。   这个是留给一些公司或者开发者自行更改的，broker做的再好，也不能满足所有的需求场景，一些同学可能还是需要fork代码自己修改。 

我看后续能否进行调整一下，直接binary routing判断，然后就进行转发。 另外我会将binary routing附带的那个文本，看能解析的更快，这样也可以保证信息都能记录全。

**Comment by hupeiD** [comment]
嗯，按照需求自行更改是应该的，权当是想告诉BinaryRoutingMetadata在发送前没强制要求routingText必须附带，但是解析时却又不能为空，这里显得比较矛盾而已，只是个小问题。

然后，是使用RSocket Broker的Filter机制来实现前面的场景时还是会有些不便之处。比如，这里仅仅是想要Broker端收集数据，那么RSocketBrokerHandlerRegistry就可能没有对应的Service。在RSocketFilter#run(RSocketExchange)处理完之后就会报RST-900404，尽管业务已经处理完毕了。当然也可以在Broker端构造一个空的Service来接收，只是这样显得不够优雅罢了。所以可能增加某些状态来标记当前请求其实是不需要路由的，或者是经过处理后才不再需要路由转发了，这样会不会更好。

**Comment by linux-china** [comment]
可以给这个 RSocketExchange添加一个状态位，如-1就表示不需要再进行下一步路由，直接返回error就可以吧？ 如果是这个需求，还是非常容易实现的，而且也不会对性能有影响。
