### ISSUE TITLE
RSocket Java SDK 1.1.0兼容测试

### ISSUE THREAD

**Issue by linux-china** [alibaba/alibaba-rsocket-broker#92]
RSocket Java SDK 1.1.0使用 reactor-core 3.4.0，需要和RSocket Broker进行兼容性测试。 目前主要测试点包括：

* RSocket Java SDK 1.0.3 和 reactor-core 3.4.0 兼容测试
* RSocket Java SDK 1.1.0和 reactor-core 3.3.x 兼容测试
* RSocket Broker和RSocket Java SDK 1.1.0兼容测试
* Spring Boot 2.3.x和RSocket Java SDK 1.1.0兼容测试
* Spring Boot 2.4.0和RSocket Java SDK 1.0.3兼容测试
* Scalecube cluster 2.6和Reactor Netty 1.0的兼容

最后给出对应的报告，在应用出现问题时，首先要检查依赖兼容性问题。

**Comment by jimichan** [comment]
rsocket 1.1.0 使用了reactor-netty-core-1.0.0
但是scalecube 2。6.0-RC7。（目前MVN最新的了已经）使用了reactor-netty-core-0.9.*的版本。


bootstrap方法被移除了，会导致scalecube运行错误


```java
/**
	 * @deprecated  as of 0.9.10. Use the methods exposed on {@link TcpServer} level. The method
	 * will be removed in version 1.0.0.
**/
@Deprecated
	public final TcpServer bootstrap(Function<? super ServerBootstrap, ? extends ServerBootstrap> bootstrapMapper) {
		return new TcpServerBootstrap(this, bootstrapMapper);
	}
```

**Comment by linux-china** [comment]
也不用担心， Broker是独立应用，可以使用不同的版本的RSocket，而RSocket Broker客户端兼容是非常重要的，毕竟要和应用进行整合和部署的。 目前RSocket Broker客户端应用和RSocket 1.1.0的测试是没有问题的，现在主要是Broker的测试。

**Comment by jimichan** [comment]
@linux-china 请教个题外问题：）

最近在研究Elasticsearch,ES是一个主从分布式架构，集群发现、一致性、内部RPC、非阻塞编程代码非常复杂。

所以如果使用类似broker模式：
1. 中心化的broker管理集群的元信息、路由转发、协调工作
2. 数据节点只负责索引分片、分片搜索的计算服务
3. 对外服务通过一个统一http网关来协调，调用各分片RPC服务，返回的数据、统一整合后处理后返回给客户端
4. 当然rpc通信是基于RSocket

这种思路大概是否有可行性

**Comment by linux-china** [comment]
>>  对外服务通过一个统一http网关来协调，调用各分片RPC服务，返回的数据、统一整合后处理后返回给客户端

可以的，没有问题的。  你可以直接对外暴露RSocket协议提供给你客户端，当然也可以HTTP，兼容之前的客户端。

**Comment by hupeiD** [comment]
@linux-china 你好，想问问broker的设计里，事件广播在应用端可以接收到么。按照下面的例子，broker端是可以正常接收到事件消息的，但放在应用端就收不到了。还是这是最新版本的原因，或者其他的原因呢？

```java
@SuppressWarnings({"deprecation", "rawtypes"})
@Component
public class CloudEventProcessor {

    private static final Logger log = Loggers.getLogger(CloudEventProcessor.class);

    public CloudEventProcessor(TopicProcessor<CloudEventImpl> reactiveCloudEventProcessor) {
        reactiveCloudEventProcessor.subscribe(cloudEvent -> {
            AttributesImpl attributes = cloudEvent.getAttributes();
            log.info(attributes.toString());
        });
    }
}
```

**Comment by hupeiD** [comment]
@linux-china  你好，想问问broker的设计里，事件广播在应用端可以接收到么。按照下面的例子，broker端是可以正常接收到事件消息的，但放在应用端就收不到了。还是这是最新版本的原因，或者其他的原因呢？二是想问问如果应用节点想要获得自己在broker生成的uuid或者instanceId该如何取得呢？

```java
@SuppressWarnings({"deprecation", "rawtypes"})
@Component
public class CloudEventProcessor {

    private static final Logger log = Loggers.getLogger(CloudEventProcessor.class);

    public CloudEventProcessor(TopicProcessor<CloudEventImpl> reactiveCloudEventProcessor) {
        reactiveCloudEventProcessor.subscribe(cloudEvent -> {
            AttributesImpl attributes = cloudEvent.getAttributes();
            log.info(attributes.toString());
        });
    }
}
```

**Comment by linux-china** [comment]
接入方的UUID在  RSocketAppContext.java  中。 

给接入方发送事件，  在 RSocketBrokerResponderHandler.java中，有一个fireCloudEventToPeer()  API，发送cloud events事件就可以啦。  广播其实就是找到每一个接入方对应的RSocketBrokerResponderHandler，然后调用fireCloudEventToPeer()进行发送即可。


客户端处理事件的代码可以参考：  https://github.com/alibaba/alibaba-rsocket-broker/blob/master/alibaba-rsocket-spring-boot-starter/src/main/java/com/alibaba/spring/boot/rsocket/InvalidCacheEventProcessor.java

**Comment by linux-china** [comment]
服务的消费端和服务发布端都已经兼容RSocket Java 1.1.0，Spring Boot 2.4。 但是RSocket Broker目前由于gossip问题，还无法升级到RSocket Java 1.1.0，但是作为独立的Broker应用，不会影响到所有接入的应用。

**Comment by linux-china** [comment]
请查看1.1.0的发布说明： https://github.com/alibaba/alibaba-rsocket-broker/releases/tag/1.1.0
